language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: david.beale@bealearts.co.uk
  api_key:
    secure: peolFTSw8dh06eKurfIv8atSnsyZK60Ah+rGX0KYzjeiX+3C2f4jZdn4qt25XsObB61loJ0qFcdwjefleXUroedu9Qwmr2vC4SV/yFtKiNmCC4j9AsMzVllz2BPpvL3SV2+01IQpZLfM8H2AG/x7D764WQtH2UL8ATHWMG7kEULPmzC24xdvO2jybx0KXNfeoP8iiZGBeaihabCO8isryo90MZOsXJrws9oAIghawz9S48A7bqBy+QLrOVDQs5zPovn3ufp2dIydNzCWyV2Wstth3yHj9r+Y+wlxWlEqXJa1Lj+M8e4/50nBaFJwLxCmSvi1SKGSQk9ytWf31s7b1GjFyCIzDCPy7KdK5pw/Yyo64QYqWCdXmcLMB1DXMoUZtVsF5Cq5RR421lPZOaXcyxRrQajOkEdPEGSSguhhhk0PhoET46OZaYw2bn0M8krszHnTlCeWq+sjPQd8zAtXepv5u119xBWfg6CuRsFm+qgLkrVC5v7mkI4VH9IH1hfr9OZTqYWLvXT/vKe4dRHX5rHMAIha5EMErUsX/S8Bg2O+d0Sk54RF4aVpKw2eouwvnhVck/SUDKW8FvhyXa6VHCYaB/XhkUYsKcZgogKKl7H9Pstf8oRzyOrnUiEAB1hn1/azPLZw3pk58MiKfe7tthvN6l45EcxKwtsO9nMHDaA=
  on:
    all_branches: true
    tags: true
    repo: bealearts/poor-mans-proxy-decorate-property
